### ISSUE TITLE
Develop your ABCI app quick guide

### ISSUE THREAD

**Issue by gamarin2** [cosmos/cosmos-academy#11]
Computer science = build complex black boxes with easy interfaces. 
You obtain abstraction levels that allow software developers to build things without understanding lower levels. All they have to understand is how the interface work.

Complex black box -> tendermint

Easy interface -> ABCI app, 3 messages to implement. 

**Goal of quick guide** : Provide a guide for every developer to build a zone without understanding lower level stuff. Need to explain what are the 3 messages they need to implement and give a general sense of the interface. Maybe take sdk as example.

Note : Add IBC section
Edit: Focus quick guide on Cosmos-SDK instead of 3 messages

**Comment by Chjango** [comment]
We don't need ABCI docs or blog posts about ABCI. I've discussed this thoroughly with Jae. Lets not put any work into ABCI.
