### ISSUE TITLE
Tutorial: SDK Modules

### ISSUE THREAD

**Issue by jbibla** [cosmos/cosmos-academy#14]
@sunnya97's tech workshop: [Implementing a SDK Module](https://allinbits.slack.com/files/U5YFPRAUF/FCH96AN1M/wanxiang-sunny-slides.key)

**Comment by Chjango** [comment]
# Project Description
Cosmos-SDK “How to Build a Module” blog post tutorial

## Status
Gautier is working on a tutorial for building an example module

**Project Deadline: Apr 28**

**Comment by zramsay** [comment]
handled in SDK repo / docs refactor
