### ISSUE TITLE
Tendermint 101

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-academy#16]
@Chjango assign Federico when he is in github.

**Comment by Chjango** [comment]
# Project Description
- Tendermint related links/docs
- Unclear what the needs are here yet. Potentially no extra work needs to be done since we can reference existing docs. Some updates need to be made however upon shipping final Tendermint release.

**Comment by fedekunze** [comment]
- [ ] Finish [Proof](https://tendermint.readthedocs.io/en/master/specification/byzantine-consensus-algorithm.html) section of Tendermint Consensus

**Comment by zramsay** [comment]
superseeded by #31. The landing page will point to tendermint.rtfd.io, which has Tendermint 101/102 sections, etc. Those docs themselves could use an update but that's a seperate issue
