### ISSUE TITLE
Content: Glossary of Terms

### ISSUE THREAD

**Issue by Chjango** [cosmos/cosmos-academy#24]
# Project Description

Define all the jargon used in Cosmos. Will be used on the webpage and in the Academy.

- [ ] candidate
- [ ] cosmos
- [ ] cosmos SDK
- [ ] elliptic curve
- [ ] finite field
- [ ] gf-2-255-19
- [ ] hub
- [ ] IBC packets
- [ ] PoS
- [ ] PoW
- [ ] signature
- [ ] sharding
- [ ] stake
- [ ] tendermint
- [ ] testnet
- [ ] token
- [ ] validator
- [ ] validator set
- [ ] zksnarks
- [ ] zone

**Project Deadline: Apr 4**

**Comment by fedekunze** [comment]
This could be also useful as an appendix for the Gitbook

**Comment by zramsay** [comment]
https://github.com/tendermint/aib-data/blob/develop/json/glossary.json

**Comment by zramsay** [comment]
this is done. terms that still need to be explained are self-documented in the glossary.json
