### ISSUE TITLE
Example SDK App: Democoin

### ISSUE THREAD

**Issue by Chjango** [cosmos/cosmos-academy#25]
# Project Description

Set up and update [democoin](https://github.com/cosmos/cosmos-sdk/pull/695#issuecomment-376959153) repo.

**Comment by cwgoes** [comment]
I'm still glad to do this but per discussion on https://github.com/cosmos/cosmos-sdk/pull/695 we may want to wait until the SDK is a bit more stable.

**Comment by cwgoes** [comment]
Waiting on discussion at next meeting - https://github.com/cosmos/cosmos-sdk/pull/695#issuecomment-377704208

**Comment by cwgoes** [comment]
Per discussion of SDK team - we're postponing this a few weeks until the SDK is sufficiently stable that maintenance by the Academy team won't be too onerous.

**Comment by zramsay** [comment]
exists in SDK repo
