### ISSUE TITLE
Register interest to become an initial validator

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/cosmos-academy#4]
This issue is just so that we have an overview who in the community would like to participate in running some of the testnet validators and maybe even try to run an actual validator.

**Comment by kjaiswal** [comment]
I would like to become one. What details if any do you need from me?

**Comment by adrianbrink** [comment]
Awesome, thanks for letting us know.

Just check back regularly into our rocket chat and our github.

**Comment by jackson-jackson** [comment]
I'm interested in becoming a validator.

**Comment by Orangem21** [comment]
I'm interested in becoming a validator. from China

**Comment by makoshan** [comment]
I'm interested in becoming a validator.

**Comment by xtrapower** [comment]
I'm interested too. I'm staking for a living so i'm curious to learn in a testnet environment and provide a stable validator later on.

**Comment by adrianbrink** [comment]
@xtrapower A testnet with the staking and delegation should be up by October.

**Comment by kdvalentine** [comment]
I'm interested in becoming a validator.

**Comment by xtrapower** [comment]
@adrianbrink Very exited! Cosmos is a great project with a great team behind it. And October is not too far away...

**Comment by mdyring** [comment]
I'm in

**Comment by themonsterbit** [comment]
Hi, we has been preparing the validator of cosmoshub.

Kafka.Lee and I am a same team. :)

**Comment by themonsterbit** [comment]
Kafka.Lee and I am a same team.

We has been preparing for validator of Cosmoshub. :)

**Comment by adrianbrink** [comment]
Awesome to have all this interest guys :-)

**Comment by techorb** [comment]
Will keep an eye in rocket chat, but I'm extremely interested. I've been a fan of tendermint since I first read the wp nearly a year ago, excited about cosmos, and happy to see some signs of collaboration w/ parity team.

**Comment by themonsterbit** [comment]
It is good to make a web or board that anyone can introduce yourself to be a validators.

Like as this
https://forum.lisk.io/viewforum.php?f=48

**Comment by nuevax** [comment]
me too would like to become a validator

**Comment by mrgrshift** [comment]
Hi, I'm interested in becoming a validator. too, sign me :100:

**Comment by Chjango** [comment]
Expressing interest as well! Woo! Team Cosmonauts!

**Comment by BlackAtom1** [comment]
Expressing interest to validate.

**Comment by zramsay** [comment]
those interested in becoming a validator should check out the https://github.com/cosmos/gaia repo and try joining the `gaia` testnets https://blog.cosmos.network/quickstart-guide-connecting-to-the-latest-testnet-57568e2d6b9
