### ISSUE TITLE
CI for example apps

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/cosmos-academy#61]
CircleCI should build and test all example apps.

**Comment by jolesbi** [comment]
@greg-szabo @zramsay what do you think about this?

**Comment by zramsay** [comment]
fo sho

**Comment by greg-szabo** [comment]
Sure CI is a good idea for any code you write and CircleCI is good at fulfilling these kind of things. What is this issue for exactly? I don't see any example apps or tests.

**Comment by jolesbi** [comment]
there are 2 open PR's with example apps in them.

**Comment by zramsay** [comment]
IMO example apps should be in https://github.com/cosmos/cosmos-sdk/tree/develop/examples

**Comment by zramsay** [comment]
obsolete, examples apps are ~ tested
