### ISSUE TITLE
Blog: Introduce Cosmos Academy

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/cosmos-academy#8]
It should be published on medium

**Comment by themonsterbit** [comment]
The page shows error. It need to be fixed.

**Comment by jolesbi** [comment]
@Chjango maybe we can publish the list of current and future content in the form of a blog post when we're ready!

**Comment by zramsay** [comment]
meh. we'll have a medium blog post announcing the whole content/docs revamp that'll basically cover this
