### ISSUE TITLE
Produce a roadmap for the launch of the COSMOS hub

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/cosmos-academy#9]
Internally we have been discussing the roadmap. The idea is to take that internal roadmap, prettify it and create graphics for the timeline of it.

[Launch Plan](https://docs.google.com/document/d/1sDTfpFEh1S1EPMDeNp9-FhgpHv-G693qGqOYLjF-4rc/edit)

**Comment by zramsay** [comment]
https://github.com/cosmos/cosmos.github.io/pull/97
